Add Random Generator and unit tests
T-Syme/ECSE437Project pull request #12
Opened 2022-11-19 17:04 UTC by T-Syme

- When a RandomGenerator is created, a full list of possible numbers is created, then shuffled randomly so there cannot be repeated numbers.
- The method getNext() returns the next number from the shuffled list
- Unit tests were written for getNext()

2022-11-19 17:32 UTC, T-Syme commented
Running the tests locally using Maven test
![image](https://user-images.githubusercontent.com/70815823/202863912-e404f083-2ead-416f-bbf3-f63d73291f9c.png)

2022-11-19 20:21 UTC, hanagustyn requested changes
The code looks good. Please see my comment before merging the code.

I think a good next step for the random generator class would be to create a random letter generator as well.

2022-11-19 20:21 UTC, hanagustyn commented on src/test/java/RandomGeneratorTest.java
> +            fail();
Adding a string message to the fail() method will help debug any errors. This also applies for line 45.

2022-11-19 21:16 UTC, T-Syme commented
I'm not sure I understand what the random letter generator would be used for. The bingo boards that I've seen seem to use numbers. Was there another purpose for it?
![image](https://user-images.githubusercontent.com/70815823/202871879-d8c7264f-90ba-4b94-9745-f52b125257b0.png)

2022-11-19 21:39 UTC, hanagustyn commented
I think Bingo usually has a letter and a number associated to it. For example, when someone calls out a slot they would say B12 which means you can cover that square if you have 12 in the B column.

2022-11-19 21:40 UTC, hanagustyn approved these changes
Looks good! Feel free to merge.

2022-11-19 21:46 UTC, T-Syme commented
Huh, I didn't realize that was a thing. 
What do you think if I created an object and returned that? It could look something like this:
**RandomValue**
- randomValue.column --> number 0-4 (for b-i-n-g-o)
- randomValue.value --> number 1-75 (for bingo numbers)

2022-11-19 21:58 UTC, hanagustyn commented
Yea sounds good to me. But this would be in addition to the random generator you created, right? Because I think that is still useful for generating the game board.

2022-11-19 22:01 UTC, T-Syme commented
That's true. I can add another method that returns an array of 24 random values (5x5 with 1 free) for generating boards

2022-11-19 22:11 UTC, hanagustyn commented
I actually have implemented some of that for the game board class already. I think I can just make an instance of RandomGenerator and then get 24 values from it.

2022-11-19 22:12 UTC, hanagustyn commented
But I could also just implement that in the GameBoard class itself. Maybe that makes more sense?

2022-11-19 22:18 UTC, T-Syme commented
Yes, I think it would be fine to call getNext() 24 times. I think it would be nice to generate all the random numbers from the same class

2022-11-19 22:20 UTC, hanagustyn commented
Ok, sounds good. I'll do that.

2022-11-20 01:17 UTC, T-Syme commented
Added the RandomValues as mentioned above
Using separate lists and iterators to make sure they don't clash when generating boards vs moves

2022-11-20 14:43 UTC, hanagustyn approved these changes
Looks good!

2022-11-20 15:49 UTC, merged